#!/bin/sh /etc/rc.common

USE_PROCD=1
START=90

enable=$(uci get natfrpc.@natfrpc[0].enabled)
command=$(uci get natfrpc.@natfrpc[0].command)

start_service() {
    
	[ $enable = "0" ] && exit 0

    procd_open_instance SakuraFrp

    procd_set_param command /etc/natfrpc/natfrpc.sh
	
    procd_append_param command $command # 请修改此行为您的隧道启动参数，同时可添加远程控制隧道启停等配置
    procd_set_param env LANG=zh_CN.UTF-8 # 用于显示中文日志，删除即显示英文日志
    procd_set_param limits nofile="unlimited"
    procd_set_param respawn 300 5 10
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_add_jail natfrp log
    procd_close_instance
}

stop_service() {
    service_stop /etc/natfrpc/natfrpc
}
